name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool

    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run tests
      run: make check

    - name: Distcheck (verbose)
      run: make distcheck V=1
